### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by ViperCode7** [reditec/open-rpf#2]
I don't know what I did wrong, I have both windowsdesktop-runtime-7.0.0 and windowsdesktop-runtime-7.0.15 installed, but the app is not launching.

**Comment by ViperCode7** [comment]
Try 1: Event log
_Description: A .NET application failed.
Application: Simple.RPF.Viewer.exe
Path: E:\a\Simple.RPF.Viewer.exe
Message: The application to execute does not exist: 'E:\a\Simple RPF Viewer.dll'._

Renamed the dll with dots to spaces.

Try 2: Message prompt
_You must install .NET Desktop Runtime, x64, 7.0.12_

OK, but I have installed 7.0.0 and 7.0.14... installed 7.0.12 anyway.

Try 3: Event Log
_Description: A .NET application failed.
Application: Simple.RPF.Viewer.exe
Path: E:\a\Simple.RPF.Viewer.exe
Message: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
Failed to run as a self-contained app.
-The application was run as a self-contained app because 'E:\a\Simple RPF Viewer.runtimeconfig.json' was not found.
-If this should be a framework-dependent app, add the 'E:\a\Simple RPF Viewer.runtimeconfig.json' file and specify the appropriate framework._

OK, renamed everything with dots in its name to spaces and now it works.
IDK why github offers files with dots in the file name instead of spaces.
Like Simple.RPF.Viewer.dll should have been Simple RPF Viewer.dll

https://github.com/reditec/open-rpf/releases

![image](https://github.com/reditec/open-rpf/assets/6399179/30de9b1d-429c-456a-a334-1cdc8294bd7d)

**Comment by reditec** [comment]
Thank you, @ViperCode7 for looking into this.
I will rename the executable in the future to SimpleRPFViewer. This will very likely fix the issue with the dots :-)
